version: '3.8'
services:
  mongoDb:
    image: mongo:5
    container_name: mongo-lambda
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGODB_DATABASE: lambda-gymnastic
    volumes:
      - /mongo:/data/db
    networks:
      - lambda-network

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    env_file: ".env"
    container_name: lambda_database
    networks:
      - lambda-network
    volumes:
      - /postgres:/var/lib/postgresql/data

  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached      
    ports:
      - ${PORT}:5555
    restart: always
    env_file: ".env"
    depends_on:
      - db
      - mongoDb
    container_name: lambda_devcontainer
    networks:
      - lambda-network

  

networks:
  lambda-network:
    driver: bridge